name: Publish to GitHub NPM Registry

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger the workflow on

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Change to your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build  # Change this to your build command

      - name: Publish to GitHub NPM Registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc
          echo "@<github_username>:registry=https://npm.pkg.github.com/<organization_or_repository>" >> ~/.npmrc
          npm publish
